AWSTemplateFormatVersion: 2010-09-09
Description: Photo Album Bot
Resources:
  LexBot:
    DependsOn: BotRuntimeRole
    Type: AWS::Lex::Bot
    Properties:
      IdleSessionTTLInSeconds: 300
      Name: "searchPhotoCF"
      RoleArn: !GetAtt BotRuntimeRole.Arn
      DataPrivacy:
        ChildDirected: false
      BotFileS3Location:
        S3Bucket: code-hongyi
        S3ObjectKey: SearchPhotos-DRAFT-GHPLJQNTLA-LexJson.zip

  BotRuntimeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lexv2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
