AWSTemplateFormatVersion: 2010-09-09
Description: Photo Album Bot
Resources:
  LexBot:
    DependsOn: BotRuntimeRole
    Type: AWS::Lex::Bot
    Properties:
      IdleSessionTTLInSeconds: 300
      Name: "searchPhotoCFTEST"
      RoleArn: !GetAtt BotRuntimeRole.Arn
      DataPrivacy:
        ChildDirected: false
      BotFileS3Location:
        S3Bucket: code-hongyi
        S3ObjectKey: SearchPhotos-DRAFT-GHPLJQNTLA-LexJson.zip

  LexBotVersion:
    Type: AWS::Lex::BotVersion
    Properties: 
      BotId: !Ref LexBot
      BotVersionLocaleSpecification: 
        - BotVersionLocaleDetails:
            SourceBotVersion: DRAFT
          LocaleId: en_US
      Description: Production Version

  LexBotAlias:
    Type: AWS::Lex::BotAlias
    Properties: 
      BotAliasName: prod
      BotId: !Ref LexBot
      BotVersion: !GetAtt LexBotVersion.BotVersion
      Description: Production Alias

  BotRuntimeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lexv2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
