AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Photo Album
Resources:
  Random:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: assignment2-b1
      WebsiteConfiguration:
        IndexDocument: index.html
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a46d225a-6262-4049-907a-b69449375ba9
  assignment2searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: >-
        arn:aws:iam::814655805539:role/service-role/assignment2-search-photos-role-f4f72gsx
    Metadata:
      'AWS::CloudFormation::Designer':
        id: da83c70f-b283-414a-af81-ea585ad3dfcb
  assignment2indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::814655805539:role/service-role/assignment2-index-photos-role-cf6f8jzp
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1f449acc-f70e-464f-ab84-3a7832b9a0fd
  elasticsearch:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: 'assignment2'
      EngineVersion: 'OpenSearch_1.3'
      ClusterConfig:
        InstanceType: 't3.small.search'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              AWS: 'arn:aws:iam::814655805539:role/service-role/assignment2-index-photos-role-cf6f8jzp' 
            Action: 'es:*'
            Resource: !Ref elasticsearch
          -
            Effect: 'Allow'
            Principal:
              AWS: 'arn:aws:iam::814655805539:role/service-role/assignment2-search-photos-role-f4f72gsx'
            Action: 'es:*'
            Resource: !Ref elasticsearch
Outputs:
  WebsiteURL:
    Description: URL for Website Hosted on S3
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
Metadata:
  'AWS::CloudFormation::Designer':
    da83c70f-b283-414a-af81-ea585ad3dfcb:
      size:
        width: 60
        height: 60
      position:
        x: 140
        'y': 90
      z: 1
      embeds: []
    a46d225a-6262-4049-907a-b69449375ba9:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 170
      z: 1
      embeds: []
    1f449acc-f70e-464f-ab84-3a7832b9a0fd:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
